server:
  port: 8082
spring:
  application:
    name: springboot-opentelemetry-starter

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s

  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,metrics