server:
  port: 8082
spring:
  application:
    name: springboot-opentelemetry-starter

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318
  tracing:
    sampling:
      probability: 1.0


#management.expor