    input {
        kafka {
                bootstrap_servers => "http://broker:29092"
                topics => ["logs"]
        }
    }

    filter {
          json {
             source => "message"
             target => "parsed_log"
          }

        mutate {
          rename => {
            "log_message" => "message"
          }
          remove_field => ["message"]

          add_field => {
             "loglevel" => "%{[parsed_log][level]}"
             "user" => "%{[parsed_log][message]}"
          }
        }

        mutate {
                      gsub => [
                            "user", "User logged in ", ""
                          ]
        }

         json {
                     source => "user"
                     target => "user_json"
                  }
    }

    output {
        stdout {
            codec => rubydebug
          }
      elasticsearch {
        hosts => "elasticsearch:9200"
        index => "helloworld-springboot-app"
      }
    }