# docker-compose.yml
version: '3.8'
services:

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.4.0
    ports:
      - "3200:3200"  # Tempo HTTP
#      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    command:
      - "--target=all"
      - "--storage.trace.backend=local"
      - "--storage.trace.wal.path=/tmp/tempo/wal"
      - "--auth.enabled=false"
      - "-config.file=/etc/tempo.yml"

networks:
  default:
    driver: bridge